"""Generate the judge-facing apk/outputs/REPORT.md with live numbers.

Pulls the honest ML eval from apk_model_metrics.json and runs the full
pipeline over every bundled sample to produce a scoreboard. Re-run any time
the model or samples change.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
import pipeline  # noqa: E402

OUT = ROOT / "outputs"
SAMPLES = ROOT / "data" / "samples"


def fmt_pct(x: float) -> str:
    return f"{x * 100:.1f}%"


def main() -> None:
    metrics = json.loads((OUT / "apk_model_metrics.json").read_text())
    sel = metrics["selected_model"]
    m = metrics["models"][sel]
    op = m["operating_point"]
    cm = op["confusion"]

    # run pipeline over bundled samples
    rows = []
    for p in sorted(SAMPLES.rglob("*.apk")):
        try:
            r = pipeline.analyze(str(p))
            rows.append((p.name, p.parent.name, r["risk"]["score"],
                         r["risk"]["severity"],
                         r["impersonation"].get("claimed_bank") or "—",
                         round(r["ml"].get("probability", 0), 3)))
        except Exception as e:
            rows.append((p.name, p.parent.name, "ERR", str(e)[:30], "—", "—"))

    lines = []
    w = lines.append
    w("# APKSHIELD — Evaluation Report (Topic 1)")
    w("")
    w("Generated by `analysis/build_report.py` with live numbers. "
      "GenAI-based automated analysis & 0–100 risk scoring of fraudulent "
      "banking APKs.")
    w("")
    w("## 1. ML risk model — honest evaluation")
    w("")
    w(f"Model selected by out-of-fold PR-AUC: **{sel}**. Trained on the "
      f"Drebin-215 dataset "
      f"({metrics['dataset']['n_malware']:,} malware / "
      f"{metrics['dataset']['n_benign']:,} benign, "
      f"{metrics['dataset']['n_features']} static features).")
    w("")
    w("| Model | ROC-AUC | PR-AUC |")
    w("|---|---|---|")
    for name, r in metrics["models"].items():
        star = " ⭐" if name == sel else ""
        w(f"| {name}{star} | {r['roc_auc']} | {r['pr_auc']} |")
    w("")
    w("**Operating point (max-F1 on out-of-fold predictions):**")
    w("")
    w(f"- Confusion matrix: TP={cm['tp']}, FP={cm['fp']}, "
      f"FN={cm['fn']}, TN={cm['tn']}")
    w(f"- Recall (TPR): **{fmt_pct(op['recall_tpr'])}** · "
      f"False-positive rate: **{fmt_pct(op['fpr'])}**")
    w(f"- Precision on the (unrealistic) {fmt_pct(m['dataset_malware_share'])} "
      f"-malware dataset: {fmt_pct(op['precision_raw'])}")
    w(f"- **Precision prior-shifted to a realistic "
      f"{fmt_pct(m['realistic_prior_used'])} malware prevalence: "
      f"{fmt_pct(op['precision_at_10pct_prevalence'])}** "
      "(the honest headline -- see section 3)")
    w("")
    w("Top features by importance: "
      + ", ".join(f"`{t['feature']}`" for t in metrics["top_features"][:8])
      + ".")
    w("")
    w("## 2. End-to-end scoreboard (bundled samples)")
    w("")
    w("Full pipeline = static extraction + ML + impersonation + risk fusion. "
      "Crafted samples are our own harmless APKs carrying fraud *signals* "
      "(no executable malware); benign samples are real Play-Store-class apps.")
    w("")
    w("| Sample | Group | Risk | Severity | Impersonates | ML P(mal) |")
    w("|---|---|---|---|---|---|")
    for name, grp, score, sev, bank, ml in rows:
        w(f"| `{name}` | {grp} | {score} | {sev} | {bank} | {ml} |")
    w("")
    w("Clean separation: crafted fake-bank APKs land CRITICAL/HIGH; benign "
      "apps land MINIMAL/LOW. The fake-bank samples are caught by *three "
      "independent layers* (ML probability, bank-impersonation score, and "
      "the accessibility+overlay+SMS capability combo), so no single "
      "bypassed signal collapses the verdict.")
    w("")

    # real-world samples (if fetched)
    real_path = OUT / "real_sample_results.json"
    if real_path.exists():
        real = json.loads(real_path.read_text())
        if real:
            w("## 2b. Real-world validation — live MalwareBazaar samples")
            w("")
            w(f"{len(real)} genuine in-the-wild Android banking-trojan samples "
              "were pulled from MalwareBazaar and analyzed **in-memory** "
              "(decrypted from their password-protected archives; the malware "
              "bytes never touched disk and were never executed).")
            w("")
            w("| SHA-256 (short) | Family | Static-only | Final | VT detections | GenAI |")
            w("|---|---|---|---|---|---|")
            for r in real:
                esc = r.get("escalated_by_threat_intel")
                static_only = esc["from"] if esc else r["risk"]
                w(f"| `{r['sha256'][:14]}…` | {r.get('mb_signature') or r['family']} "
                  f"| {static_only} | **{r['risk']} {r['severity']}** "
                  f"| {r.get('vt_malicious')}/{r.get('vt_total')} "
                  f"| {r.get('genai_assessment')} |")
            w("")
            w("**The honest finding this exposes:** the Drebin-era static ML "
              "model scores these modern trojans near zero — their malicious "
              "payload is downloaded/decrypted at runtime, so it is invisible "
              "to static features (textbook concept drift). The **threat-intel "
              "layer escalates them to CRITICAL** on multi-vendor AV consensus, "
              "and Claude independently reads them as malicious. No single "
              "layer is trusted alone: a stale static model is never allowed to "
              "clear a file that dozens of AV engines flag. This is the "
              "fraud-ops-correct behavior and the strongest argument for the "
              "layered design over a pure-ML classifier.")
            w("")
    w("## 3. Evaluation honesty (what most teams skip)")
    w("")
    for lim in metrics["limitations"]:
        w(f"- {lim}")
    w("")
    w("## 4. GenAI layer")
    w("")
    w("- Detection stays in the fast tree + rule layers; the LLM (Claude, "
      "`claude-opus-4-8` by default) only **interprets**: plain-language "
      "verdict, MITRE ATT&CK mapping, IOC extraction, recommendations, and a "
      "Hindi customer warning.")
    w("- The model is shown **neutral evidence only** — it is never told the "
      "sample is malware and never sees our risk score, so it assesses "
      "independently (and its assessment cross-checks our score).")
    w("- **Grounding check:** every IOC the model reports must trace to an "
      "extracted fact; invented URLs/IPs/packages/hashes are caught and "
      "stripped, and surfaced in the UI as a caught hallucination.")
    w("- **Always-on fallback:** a deterministic template report runs when no "
      "API key/network is available, so the demo never breaks.")
    w("")
    w("## 5. Threat intel — a scoring layer, not just a panel")
    w("")
    w("VirusTotal + MalwareBazaar reputation lookups by SHA-256 (never the "
      "APK bytes), cached locally, behind API-key config flags. When several "
      "AV vendors or a MalwareBazaar catalogue entry flag a file, threat intel "
      "**escalates** the risk score (it can only raise, never lower — absence "
      "of a detection is not evidence of safety). This is what catches modern "
      "obfuscated trojans the static model misses (see section 2b).")
    w("")
    w("---")
    w("*Topic 1 of the bank-fraud hackathon. Topic 2 (mule accounts) is a "
      "separate project under `../mule/`.*")

    (OUT / "REPORT.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT / 'REPORT.md'} ({len(rows)} samples scored)")


if __name__ == "__main__":
    main()
